### ISSUE TITLE
Future of project

### ISSUE THREAD

**Issue by ogezue** [willowtreeapps/spruce-ios#104]
Is this project still maintained (e.g support for Swift 5) or should developers look for alternatives?

**Comment by eriklamanna** [comment]
Yes, we are working on a swift 5 release as we speak

**Comment by eriklamanna** [comment]
2.1.0 should now be tagged if you use Carthage and I just published 2.1.0 to cocoapods https://cocoapods.org/pods/Spruce

Let me know if you run into any issues.
