### ISSUE TITLE
Example App: Initial value of slider not matching code snippet

### ISSUE THREAD

**Issue by wt-johncuthbert** [willowtreeapps/spruce-ios#74]
Upon initial launch of the Example App, the code snippet shows a interObjectDelay of (0.025) or 25% of .1s.  However, the actual value of the slider is 30%.  Once an adjustment is made on the slider, the value and code snippet are in sync - it is just on the initial launch of the app.

**Comment by thisIsAndrewH** [comment]
@wt-johncuthbert have a fix as soon as I can push it.

**Comment by wt-johncuthbert** [comment]
Verified the initial value is now 25% and matches the code snippet.  Also verified changing slider, value and code snippet still match.
