### ISSUE TITLE
pod - Unable to find a specification for 'Spruce'

### ISSUE THREAD

**Issue by JellyHell** [willowtreeapps/spruce-ios#78]
[!] Unable to find a specification for `Spruce`

**Comment by jacksontaylor13** [comment]
@JellyHell This seems to be an issue with your Pod repo being out of date. If you try running the command 
```
pod repo update
```
then that should refresh your local pod spec repository. Since Spruce is so new this is something a lot of people will have to do. Let me know if that fixes the issue for you.

**Comment by JellyHell** [comment]
This is OK  thanks!
