### ISSUE TITLE
Can't get view to animate

### ISSUE THREAD

**Issue by 16alexanders** [willowtreeapps/spruce-ios#89]
Hi I'm trying to animate an existing UILabel...

I have this in my viewDidLoad method:

```
HomeView.spruce.prepare(with: [.slide(.right, .severely)])
HomeView.spruce.animate([.slide(.right, .severely)])
```

But nothing happens when the view loads. I honestly don't understand what I could be doing wrong the API seems very simple. I tried explicitly casting the Label to a UIView even though it inherits from it... 
`let v = HomeView as UIView`

**Comment by evliu** [comment]
if it's in your `viewDidLoad`, it probably animates before your view appears. Try moving `.animate(` to `viewDidAppear`

**Comment by 16alexanders** [comment]
I overrode viewDidAppear and threw animate in there and it still didn't work. Also linked the animate function to an IBAction button press to control when it happens and it doesn't happen at all. I was thinking... Is this because of constraints in my code or something.

**Comment by evliu** [comment]
I see, i made an IBOutlet UIImageView and UILabel as well to test and it doesn't animate for me either. Not sure why at this point.

**Comment by jacksontaylor13** [comment]
@16alexanders Spruce should still work if you have constraints or not. Seems like something fishy is going on here haha. Any chance you can post your code (project) or a little more explanation of your view setup?

**Comment by 16alexanders** [comment]
//
//  ChoiceViewController.swift
//  
//
//  Created by Alex Sikand on 5/12/17.
//
//

import UIKit
import SwiftyButton
import FontAwesome_swift
import CZPicker
import Spruce

let globalFont = UIFont(name: "NexaBold", size: 18.0)

class ChoiceViewController: UIViewController {

    @IBAction func selectHome(_ sender: Any) {
        showPicker()

    }
    
    @IBAction func selectApartment(_ sender: Any) {
        showPicker()
        Home.spruce.animate([.slide(.down, .severely)])

    }
    
    func showPicker() {
        let min = Date()
        let max = Date().addingTimeInterval(60 * 60 * 24 * 4)
        let picker = DateTimePicker.show(minimumDate: min, maximumDate: max)
        picker.highlightColor = UIColor.flatPurple()
        picker.darkColor = UIColor.darkGray
        picker.doneButtonTitle = "Schedule a Tidy"
        picker.todayButtonTitle = "Today"
        picker.is12HourFormat = true
        picker.dateFormat = "MM/dd/YYYY"
        picker.isDatePickerOnly = true
        picker.completionHandler = { date in
            let formatter = DateFormatter()
            formatter.dateFormat = "MM/dd/YYYY"
        }
    }

    @IBOutlet weak var whereLiveLabel: UILabel!
    @IBOutlet weak var pickApartment: FlatButton! //Flatbutton: Just a UIButton subclass
    @IBOutlet weak var pickHouse: FlatButton!

    @IBOutlet weak var Apartment: UILabel!
    @IBOutlet weak var Home: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        let screenSize: CGRect = UIScreen.main.bounds
        let screenWidth = screenSize.width
        let screenHeight = screenSize.height
        
        whereLiveLabel.center.y = 70
        whereLiveLabel.center.x = 0.5 * screenWidth
        whereLiveLabel.font = UIFont(name: "NexaBold", size: 21.0)!
        
        pickApartment.titleLabel?.font = UIFont(name: "NexaBold", size: 18.0)!
        pickHouse.titleLabel?.font = UIFont(name: "NexaBold", size: 18.0)!

        Home.center.x = screenWidth / 4
        Apartment.center.x = 0.75*screenWidth
        
        Home.font = UIFont.fontAwesome(ofSize: 70)
        Home.text = String.fontAwesomeIcon(code: "fa-home")
        
        Apartment.font = UIFont.fontAwesome(ofSize: 70)
        Apartment.text = String.fontAwesomeIcon(code: "fa-building-o")
        
        pickApartment.center.x = 0.75 * screenWidth
        pickHouse.center.x = 0.25 * screenWidth
        
        
        pickApartment.color = UIColor.flatPurple()
        pickHouse.color
            = UIColor.flatPurple()
        pickApartment.cornerRadius = 8
        pickHouse.cornerRadius = 8
        
        Home.spruce.prepare(with: [.slide(.down, .severely)])
        
    }
    
    override func viewDidAppear(_ animated: Bool) {
        Home.spruce.animate([.slide(.down, .severely)])
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
   
}

**Comment by 16alexanders** [comment]
![simulator screen shot may 16 2017 4 26 04 pm](https://cloud.githubusercontent.com/assets/6835342/26132321/5e080ebe-3a54-11e7-8371-54d1800faffc.png)

**Comment by 16alexanders** [comment]
My intention is that if a user presses "Choose Home" then the 'apartment' option and logo will slide/spring offscreen to the right, and the 'home' option and logo will slide to the center. 
(vice versa for other button choice)

**Comment by jacksontaylor13** [comment]
@16alexanders So from what I can tell, it looks like you may be using `Spruce` in a different way then intended. `Spruce` is designed to animate the subviews of a view. That means when you call `yourView.spruce.animate` this will affect all of the subviews of that view. Since you are calling `Home.spruce.animate` you are trying to animate the subviews of a `UILabel` which doesn't have any subviews. For the animation that you are going for, I would say to use a basic `UIView.animate` block. 

To use Spruce, I would say this page would look great with an entrance animation. You can call `view.spruce.animate` when the view appears, and then all of the buttons on the screen will animate in at an offset. 

Hopefully this answers your question.

**Comment by 16alexanders** [comment]
I see, so I guess Spruce is used to animate the various subviews of a UIView with a certain effect / sorting function rather than animate individual views. Thanks for clarifying.
