### ISSUE TITLE
iOS 11 error 

### ISSUE THREAD

**Issue by manuel21** [willowtreeapps/spruce-ios#97]
Xcode 9
Swift 4
iOs 11

<img width="1279" alt="screen shot 2017-11-24 at 11 04 33 am" src="https://user-images.githubusercontent.com/7534410/33219332-55326894-d107-11e7-901f-e154dc500c24.png">

**Comment by ogezue** [comment]
+1

**Comment by jacksontaylor13** [comment]
@manuel21 @ogezue Is this error still happening with the new swift 4 release?

**Comment by pauloec** [comment]
Yeah, still happening @jacksontaylor13

**Comment by eriklamanna** [comment]
This appears to be solved in the Swift 5 release.
